plugins:
  detectors:
    misleading:
      MustContradictNLI:
        hf_args:
          device: cuda
  generators:
    openai:
      OpenAICompatible:
        extra_params:
          extra_body:
            chat_template_kwargs:
              enable_thinking: false
        max_completion_tokens: 32768
        max_tokens: 32768
        min_p: 0.1
        presence_penalty: 0.0
        suppressed_params:
        - n
        - frequency_penalty
        system_prompt_template: '{instruction} {thinking_prompt_smollm}'
        temperature: 0.6
        top_k: 50
        top_p: 0.95
        uri: http://lrdn0127:9000/v1
